---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-bladerose-me
  namespace: default
spec:
  secretName: kube-bladerose-me-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.kube.bladerose.me"
  dnsNames:
  - "kube.bladerose.me"
  - "*.kube.bladerose.me"
