installCRDs: false
replicaCount: 3
extraArgs:
  - --dns01-recursive-nameservers=9.9.9.9:53,1.0.0.1:53
  - --dns01-recursive-nameservers-only
podDnsPolicy: None
podDnsConfig:
  nameservers:
    - 9.9.9.9
    - 1.0.0.1