---
bootstrapPassword: admin
hostname: rancher.kube.bladerose.me
ingress:
  enabled: true
  ingressClassName: traefik
  tls:
    source: secret
  extraAnnotations:
    cert-manager.io/cluster-issuer: letsencrypt-production # Replace with your ClusterIssuer name if different
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
  extraHosts:
    - host: rancher.kube.bladerose.me
      paths:
        - path: /
          pathType: Prefix

#####
hostname: rancher.local.myhome.me
ingress:
  enabled: true
  ingressClassName: traefik
  tls:
    source: none # Disables Rancher's internal TLS management
